name: Manual Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build Mod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "25"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Allow Gradle Wrapper execution
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Upload built mod
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.event.repository.name }}-${{ github.run_number }}
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
          if-no-files-found: error
          retention-days: 14
